GAME_MODE = {
    'blitz' : 'Blitz',
    'bullet' : 'Bullet',
    'classical':'Classical',
    'correspondence': 'Correspondance',
    'puzzle': 'Puzzles',
    'chess960': 'Chess960',
    'ultrabullet': 'UltraBullet',
}

TOURNOIS = {
    "ete":"Tournois d'été",
    "confinement2":"Tournois du confinement v2",
    "2021":"Tournois de 2021"
}

CATEGORIES_DROPDOWN  = {
    'Elo':'Catégories Elo',
    '1800+':'Plus de 1800',
    '1500-1800':'Entre 1500 et 1800',
    '1300-1500':"Entre 1300 et 1500",
    '1100-1300':'Entre 1100 et 1300',
    '1100-':'Moins de 1100',
    'Age':'Catégories Age',
    "Veteran":"Veteran",
    'Senior+':"Senior+",
    'Senior': 'Seniors',
    'Cadet/Junior': 'Cadet/Junior',
    'Minime':'Minime',
    'Benjamin':'Benjamin',
    'Pupille':'Pupille',
    'Poussin':'Poussin',
    'Petit Poussin':'Petit Poussin'
}


FAMILLES = {
    'Noblet':['destructivo', 'crocro44'],
    'Deruyter':['eleo44', 'assassino_v_44', 'maeva44', 'alaintrignac'], 
    'Deschamps':['destran', 'petitponey', 'totoche12','thescoutwaiter'],
    'Le Corronc':['yohan44', 'alaan71', 'lucie-la-li','saupiquet', 'axel44'],
    "Marc":['aristouille', 'philoufou'],
    "Bockser":['teuteu44', 'fabien2008', 'piba', 'solennlastar1']
}

CATEGORIES = {
    '1800+':['destructivo', 'mrpatate', 'destran', 'tipkito', 'terriblescandinave', 'yohan44', 'saupiquet', 'axel44', 'assassino_v_44',"alianikov"],
    '1500-1800':['amzer', 'crocro44', 'c_estmoi', 'alaan71', 'atlanta135', 'aragorn_du_44', 'teuteu44','marcusson44', 'epok2619', 'vinvin10044'],
    '1300-1500':['philoufou', 'jean-loup','petitponey',"totoche12",'thescoutwaiter',],
    '1100-1300':['misterdidi27000','alaintrignac','maeva44', 'aristouille','lucie-la-li', 'clem0944','theking2010', 'thefiregun', 'leoguille', 'fabien2008','solennlastar1','piba',
         'loulou22', 'chaton0612', 'maxou07','uyssebury',],
    '1100-':['eleo44',  'adam-slmn', 'gaspardbaugas' , 'gregoune', 'math974' , 'tit44600',  'perrut'],
    'Veteran':['etienne44',],
    'Senior+': ['alaintrignac','marcusson44','petitponey'],
    'Senior': ['misterdidi27000','tipkito','yohan44','destructivo', 'crocro44', 'aragorn_du_44', 'mrpatate', 'destran', 'atlanta135', 'amzer','teuteu44', 'piba','terriblescandinave',
        'assassino_v_44','thescoutwaiter',"alianikov"],
    'Cadet/Junior': [ 'saupiquet', 'axel44',  'chaton0612',"totoche12"],
    'Minime':['adam-slmn', 'maeva44','solennlastar1', 'epok2619'],
    'Benjamin':['eloe44', 'philoufou','lucie-la-li', 'alaan71', 'clem0944', 'thefiregun','fabien2008','uyssebury',],
    'Pupille':['Pupille', 'aristouille', 'theking2010', 'jean-loup', 'loulou22', 'math974', 'maxou07', 'tit44600', 'perrut'],
    'Poussin':['gaspardbaugas', 'gregoune', 'leoguille'],
    'Petit Poussin':['familleeon']
}

ID_NOM = {
  'adam-slmn': 'Adam SALOMON',
  'misterdidi27000': 'Adien SIMON',
  'alaintrignac': 'Alain DERUYTER',
  'eleo44': 'Eléonore DERUYTER',
  'maeva44': 'Maëva DERUYTER',
  'aristouille': 'Aristide MARC',
  'philoufou': 'Philibert MARC',
  'alaan71': 'Alan LE CORRONC',
  'saupiquet': 'Axel LE CORRONC',
  'axel44': 'Axel LE CORRONC',
  'lucie-la-li': 'Lucie LE CORRONC',
  'yohan44': 'Yohan LE CORRONC',
  'atlanta135': 'Benjamin GAUTIER',
  'clem0944': 'Clément GUILLEMOT',
  'theking2010': 'Enzo LEAUTE',
  'etienne44': 'Etienne FRANCK',
  'crocro44': 'Franck NOBLET',
  'destructivo': 'Rénald NOBLET',
  'presidenten': 'Rénald NOBLET',
  'gaspardbaugas': 'Gaspard BAUGAS',
  'gregoune': 'Grégoire COAT',
  'aragorn_du_44': 'Guillaume BELLIOT',
  'mrpatate': 'Guillaume NICOLAS',
  'jean-loup': 'Jean-Loup FRANCOIS',
  'amzer': 'Jérémy LE PENHER',
  'thefiregun': 'Judikael SALIOU',
  'leoguille': 'Léo GUILLEMOT',
  'sebpingui': 'Sébastien GUILLEMOT',
  'fabien2008': 'Loan BOCKSER',
  'teuteu44': 'Nicolas BOCKSER',
  'piba': 'Marie GUIBERT',
  'solennlastar1': 'Solenn BOCKSER',
  'loulou22': 'Louis DOLEZ',
  'petitponey': 'Luc DESCHAMPS',
  'totoche12': 'Othilie DESCHAMPS',
  'destran': 'Quentin DESCHAMPS',
  'thescoutwaiter': 'Julien DESCHAMPS',
  'chaton0612': 'Manon VEILLAUD',
  'marcusson44': 'Marc BLOUET',
  'math974': 'Mathilde LAPIERRE',
  'terriblescandinnave': 'Mathis CREFF',
  'maxou07': 'Maxine LESAGE',
  'familleeon': 'Philip ou Pascal EON',
  'tipkito': 'Quentin DELTOUR',
  'epok2619': 'Raphaël DES MOUTIS',
  'tit44600': 'Tom JOUNIN',
  'uyssebury': 'Ulysse BURY',
  'assassino_v_44': 'Valentin DERUYTER',
  'c_estmoi': 'Vincent SHURGAIA',
  'vinvin10044': 'Vincent SHURGAIA',
  'perrut': 'Yakim PERRUT',
  'tamha':'Naïm MOUHAID',
  "adamsalomon":"Adam SALOMON",
  "alianikov":"Maxime POULAIN",
  "lucky777":"Luc MOREAU",
  "spilett":"Joël HERVE",
  "erare":"Emmanuel GAUTIER",
  "natiti05":"Nathalie COMPERE",
  "simonbultel":"Simon BULTEL",
  "solal_charlie":"Solal DEVAUX-LETILLY",
  "hozimax":"Maxime LAPIERRE",
  'elliot10':"Elliot AVIX",
  "martinbu44":"Martin BULTEL",
}

TEAMS_ID = {
    'cen': "Cercle d'Echecs de Nantes",
    "echiquier-de-lerdre":"Echiquier de l'Erdre",
    "echecs_sautron_pdl1":"Club d'Echecs de Sautron",
    "club-echecs-la-roche-sur-yon":"Club d'Echecs de La Roche Sur Yon",
    "cholet-49300": "Club d'Echecs de Cholet",
    "echiquier-nazairien":"Echiquier Nazairien",
    "cavalier-noir-les-herbiers-echecs":"Cavalier Noir Les Herbiers",
    "geneston-sud-loire-echecs":"Club d'Echecs de Geneston",
    "la-cavale-du-fou":"La Cavale Du Fou",
    "cebva-team":"CEBVA",
    "carquefou-echecs-matchs-du-lundi-soir-avec-la-ligue-pdl":"Carquefou Echecs",
    "cercle-dechecs-castelbriantais":"Cercle d'Echecs Castelbriantais",
    "chauche-chess-club":"Club d'Echecs de Chauche",
    "eclm": "Echiquier Club Le Mans",
    'team-reze':"Team Rezé",
    "challans":"Club d'Echecs de Challans"
}